package br.gov.to.egefaz.security.domain;

public enum Escolaridade {
	FUNDAMENTAL, MEDIO_INCOMPLETO, MEDIO, SUPERIOR_INCOMPLETO, SUPERIOR, POS_GRADUADO, ESPECIALISTA, MBA, MESTRADO, DOUTORADO;
}
